# 端口号
server:
  port: 1111

# Jasypt配置文件加密key
jasypt:
  encryptor:
    password: test
# ========================redis相关配置=====================
spring:
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 81.69.249.173 # Redis服务器地址
    port: 6380 # Redis服务器连接端口
    password: ENC(r9B8FJXprGJ/0yHlpt12/5JEfCfCuaNwaNX+PzAKpFA=) # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0